# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4735aa1cd765ee59e2103ade9df88b907dd65e30f758cb89c2201d1428cf2b7f12b334e3bc0992be597527e8e282e340971c7ee3719d0c600baa95e2aa3aa353

test:
  secret_key_base: da51ea8792025a6816680c73e2f2a3cfdc0f12fdbd1644396caf1af02877d0245b97349c48ed9320741479ad1cf3f2f8d63b31e65e8cc21370d10b7b93d297e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
